{
  homeDirectory,
  pkgs,
  stateVersion,
  system,
  username,
}:

{
  home = {
    inherit homeDirectory stateVersion username;

    packages =
      with pkgs;
      [
        age
        bat
        btop
        cloc
        curlie
        difftastic
        eternal-terminal
        eza
        fd
        fzf
        gh
        haskellPackages.hell
        jq
        just
        lnav
        pandoc
        ripgrep
        tig
        vim
        watchexec
        wget
        yazi
        yq
        zoxide
      ]
      ++ pkgs.lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
        reattach-to-user-namespace
      ];

    shellAliases = {
      ",j" = "just";
      "ls" = "eza";
      "ll" = "eza -lha";
      ",y" = "yazi";
      ",z" = "zoxide";
    };

    file = {
      ".ripgreprc".source = ./files/ripgreprc;
    };

    # NOTE: fish does not source home-manager's hm-session-vars.sh (it's POSIX
    # sh syntax), and this fish config is hand-managed rather than generated by
    # home-manager. So these vars are currently inert under fish — kept here for
    # when programs.fish is enabled (which would translate them to fish syntax).
    # Until then, set RIPGREP_CONFIG_PATH directly in ~/.config/fish/config.fish.
    sessionVariables = {
      RIPGREP_CONFIG_PATH = "${homeDirectory}/.ripgreprc";
    };
  };

  imports = [
    ./modules/wezterm
  ];

  targets.darwin = pkgs.lib.mkIf pkgs.stdenv.hostPlatform.isDarwin {
    copyApps.enable = true;
    linkApps.enable = false;
  };

  programs = {
    home-manager = {
      enable = true;
    };
  };
}
