#!/usr/bin/env sh

# tiling layout
yabai -m config layout bsp
yabai -m config window_placement second_child

# gaps
yabai -m config window_gap     3
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0

# mouse: alt + drag to move; resize by dragging window edges
yabai -m config mouse_modifier alt
yabai -m config mouse_action1  move
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on

# don't tile these
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$"      manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Dash$"            manage=off
yabai -m rule --add app="^1Password$"       manage=off
